### ISSUE TITLE
User Story - Teacher Updates Attendance Extension

### ISSUE THREAD

**Issue by carriewalsh** [carriewalsh/HereToLearn#24] opened 2019-05-22 14:30 UTC
As a teacher
on my dashboard or class show page
when I click on a red X or a green check,
instead of being redirected to a new page or a pop up,
a bubble(?) appears where I can see my options with the explanation ("present but no response")
I can click an option
and I see the attendance updated (with or without refresh?)

**Comment by wipegup** [comment] 2019-05-24 04:02
This is a duplicate of #16

**Closed as completed by wipegup** 2019-05-24 04:02 UTC
Labels: enhancement, new concept
